### ISSUE TITLE
Loops reboot

### ISSUE THREAD

**Issue by MarkWA6KBP** [km4ack/hotspot-tools2#1]
Hi Jason,

When running for the first time I attempt to "Enable Hotspot" and it asks for a reboot.  Once I reboot I get:
STATUS Enabled
STATE Inactive

"Enable Hotspot" puts me back into the reboot loop.

WLAN0 is not associated
New Buster image 
Nothing else running

Or... I'm doing something completely wrong, which is a very good possibility!  :)

Cheers!
Mark
WA6KBP

**Comment by km4ack** [comment]
You say a clean image. Did you install the hotspot or just hotspot tools?

**Comment by MarkWA6KBP** [comment]
Ahhh,  just hotspot tools.  Clearly, I missed a step or 9.

**Comment by MarkWA6KBP** [comment]
It is truly amazing how well things work when I just pay attention.  Running well now.
Sorry for the bother and thanks so much for all of your work!

Mark

**Comment by km4ack** [comment]
No worries. Glad you got it worked out. If you run across anything else, just let me know. 

73, de KM4ACK
