### ISSUE TITLE
Accepting changes to the hotspot-tools repo?

### ISSUE THREAD

**Issue by nandub** [km4ack/hotspot-tools2#10]
@km4ack I thought I heard you on one of the videos you were going to unarchive `hotspot-tools` repository, if it is true, let me know so I can push my [changes](https://github.com/nandub/hotspot-tools/tree/enhancements) into.  

The tool is very useful to me with a full desktop or not.  I made some changes that would like to contribute.

73,
de KI5LKF

**Comment by km4ack** [comment]
I did unarchive hotspot-tools and renamed it for clarity. https://github.com/km4ack/hotspot-tools-lite Please submit pull requests against the dev branch of code. 73, de KM4ACK

**Comment by nandub** [comment]
Thanks.
