### ISSUE TITLE
Wi-Fi not discorverable

### ISSUE THREAD

**Issue by Festerstoybox** [km4ack/hotspot-tools2#13]
as you can see below i have followed all your steps on your in depth video (great tutorial)

![image](https://user-images.githubusercontent.com/66978535/139839343-e7a813b2-032f-4e7e-9d5e-f6d4b8ac2a07.png)

and conky shows there is IP address (I'm connected to Ethernet too)

![image](https://user-images.githubusercontent.com/66978535/139839625-16c88418-2f8b-4136-a185-17f6272d37be.png)

however I'm not getting any Wi-Fi showing up elsewhere (tried all my RPI' and phones) no matter if it is on force hotspot or not. is there anything i can do to solve this or any advice you can give me to sort this out (had my build a pi out in field tests with great success but i now need hotspot). thank you in advance for any help i can get on this issue.

Build a pi RPI 4 4GB
Elecrow 7" screen

**Comment by km4ack** [comment]
Increase the password in hotspot tools to at least 8 characters and reboot.

**Comment by Festerstoybox** [comment]
Thank you very much, it is working perfect now.
