### ISSUE TITLE
Will it work with PiOS Bookworm?

### ISSUE THREAD

**Issue by kerk1v** [km4ack/hotspot-tools2#17]
Hello, 

I'm having trouble getting it to run with Raspberry PI OS Bookworm. 

I select "Enable Hotspot", reboot yet nothing, not even able to force hotspot

Could it be that it isn't compatible with bookworm yet? Any alternatives?

**Comment by km4ack** [comment]
Does not support bookworm. Bookworm has it's own hotspot built in.
