### ISSUE TITLE
Force hotspot didn't force it

### ISSUE THREAD

**Issue by hwdornbush** [km4ack/hotspot-tools2#2]
I assume that "force hotspot" would force the hotspot to turn on and therefore disable the connection to the assigned SSID.  I executed it but nothing happened that I could detect.  The attached screen shot shows the Force Mode is Active but the WLAN is still the local SSID.
![ForceHotspot](https://user-images.githubusercontent.com/312036/82358988-26ad1480-99bc-11ea-9792-feceee92c3ff.PNG)

**Comment by km4ack** [comment]
Thanks for the report. Can you reboot please and see if it goes into hotspot mode?

**Comment by km4ack** [comment]
Found the issue. I failed to upload a critical file to github. To fix, close auto hotspot tools and run the following two commands.
cd ~/hotspot-tools2
git pull

Now give the Force Hotspot another try. Should fix the issue.
73, de KM4ACK

**Comment by hwdornbush** [comment]
It works now.  I had to Undo force hotspot and then Force hotspot to get it working.

**Comment by km4ack** [comment]
Awesome! Glad that fixed it. Thanks for beta testing and the report. That helped me track it down.

73, de KM4ACK
