### ISSUE TITLE
Space in SSID not displaying correctly.

### ISSUE THREAD

**Issue by jrcape** [km4ack/hotspot-tools2#9]
Hi Jason,

Really enjoying your raspberry pi build a pi scripts. I ran into an issue with my home setup. I have a space in the name of my wifi network and the hotspot tools doesn't display the names correctly. I've poked around in the script and changed one line to get the Add menu working changing line 204 from

LIST=$(sudo iw dev "wlan0" scan ap-force | egrep "^BSS|SSID:" | grep SSID: | sed 's/SSID://' | awk '{ print $1 }')
echo $LIST
LIST=$(echo $LIST | sed 's/ /|/g')

to

LIST=$(sudo iw dev "wlan0" scan ap-force | egrep "^BSS|SSID:" | grep SSID: | sed 's/SSID://' | sed -z 's/\n/|/g' | awk '{ print $0 }')
echo $LIST

and that got that list working and the pi connects and disconnects from my wifi now. The two sed commands can be combined into one but I ran out of time this evening. 

The list in the manage wifi menu uses a separate call that I haven't managed to get working yet, I think I don't understand yad well enough yet. 

If I make any more progress getting things working I'll send it on to you.

Thank you for all the work you've put into all of these tools for the ham community.

73
John

**Comment by vtrunkmonkeyv** [comment]
John,

Thank you for the post. I was having the same problem. SSID has a space. I’ve managed to get it to recognize my wifi now. Still having a problem getting the info to populate on the menu though. :(

Thanks again, 
Jeff
